ui:
    present: full_screen
    layout: one_two
    identifiers:
        master:
            name: master_list
            pyui: __default__
        details:
            - name: detail_view
              pyui: sample_detail
              title: 'Detail I'
            - name: more_detail_view
              pyui: sample_more
              title: 'Detail II'
              navigation: False
    detail_items:
        - more_detail_view:
            - textfield_title
        - detail_view:
            - textview_detail
labels:
    master_list.header.title: 'Config List of Items II'
    master_list.title: 'Master List SDK III'
    master_list.delete.label: 'Erase II'
    main_view.title: 'Config Title for Master-Details SDK II'

